language: node_js
node_js:
- '0.11'
- '0.10'
deploy:
  provider: npm
  email: andrewn@datatribe.net
  api_key:
    secure: I6Xl3psEn/yJ24RKTYpQLRpNQYhVApfw+BH76Hu2FhUTiTmDq3fjxnGPCUfPoF3YgYkE6evTPhh28Mybniuti1EsSRvTzpsY0vPVQCHkyHwu0VxPJ+DXduz71D7ASEIJM0ixH+xJ6vet4+PW7PSb8SDFV6YfeJq1SV8dlRicNFo=
  on:
    tags: true
    node: '0.10'
